Customer is complaining that Metronome is no longer working in the UI on their cluster.
Note: test_i_give_up.py is meant to just quickly resolve the problem and give up on figuring out what's wrong. I would recommend not running it.
